# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# automatically load the local .env file
dotenv: .env

# require OpenZepplin, Uniswap Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - Uniswap/v3-core@1.0.0
  - overlay-market/v1-core@1.0.0-beta.4

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.10
    optimizer:
      runs: 800
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@uniswap/v3-core=Uniswap/v3-core@1.0.0"
      - "@overlay/v1-core=overlay-market/v1-core@1.0.0-beta.4"
